sudo: false
language: python
python:
  - 3.6

install: true
script: true

jobs:
  include:
  - stage: deploy
    if: type NOT pull_request AND branch IS master
    script: true
    deploy:
      script: true 
