sudo: false
language: python
python:
  - 3.5
  - 3.6

stages:
  - test
  - name: deploy
    if: (type = push) AND (branch = master)

install: echo "This is the install"
script: echo "This is the script"

jobs:
  include:
  - stage: deploy
    provider: script
    script: skip
    deploy:
      script: echo "This is the deploy"
