sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

install: echo "This is the install"
script: echo "This is the script"

jobs:
  include:
  - stage: deploy
    if: type NOT pull_request AND branch IS master
    provider: script
    script: skip
    deploy:
      script: echo "This is the deploy"
